/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.denismarkushin.plugin

import kotlin.test.Ignore
import kotlin.test.Test
import kotlin.test.assertNotNull
import org.gradle.testfixtures.ProjectBuilder

/** A simple unit test for the 'io.github.denismarkushin.greeting' plugin. */
class GradlePluginsPluginTest {

    @Test
    @Ignore("Temporary disabled")
    fun `plugin registers task`() {
        // Create a test project and apply the plugin
        val project = ProjectBuilder.builder().build()
        project.plugins.apply("io.github.denismarkushin.greeting")

        // Verify the result
        assertNotNull(project.tasks.findByName("greeting"))
    }
}