/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.denismarkushin.plugin

import io.freefair.gradle.plugins.aspectj.AjcAction
import io.freefair.gradle.plugins.aspectj.AspectJPostCompileWeavingPlugin
import org.gradle.api.JavaVersion
import org.gradle.api.Plugin
import org.gradle.api.Project
import org.gradle.api.plugins.JavaPluginExtension

private const val JCABI_FOR_JAVA_11: String = "0.25.1"
private const val JCABI_FOR_JAVA_17: String = "0.26.0"
private const val ASPECTJ: String = "org.aspectj:aspectjrt:1.9.22.1"

abstract class GradlePluginsPlugin : Plugin<Project> {

    override fun apply(project: Project): Unit =
            with(project) {
                pluginManager.apply(AspectJPostCompileWeavingPlugin::class.java)
                val javaPluginConfig = extensions.getByType(JavaPluginExtension::class.java)
                when {
                    javaPluginConfig.sourceCompatibility <= JavaVersion.VERSION_11 ->
                            addJcabi(JCABI_FOR_JAVA_11)
                    javaPluginConfig.sourceCompatibility >= JavaVersion.VERSION_17 -> {
                        addJcabi(JCABI_FOR_JAVA_17)
                        addJsr303Support()
                    }
                }
                addAspectJRuntimeForJooqIfRequired()
                addXlintIgnoreForCompileTasks()
            }

    private fun Project.addJcabi(version: String) {
        addDefaultDependency(
                configuration = "jcabi",
                dependency = "com.jcabi:jcabi-aspect:$version",
        )
    }

    private fun Project.addDefaultDependency(configuration: String, dependency: String) {
        configurations.getByName(configuration).defaultDependencies {
            it.add(dependencies.create(dependency))
        }
    }

    private fun Project.addJsr303Support() {
        dependencies.add("implementation", "org.apache.bval:bval-jsr:1.1.2")
    }

    private fun Project.addAspectJRuntimeForJooqIfRequired() {
        configurations.findByName("jooqImplementation")?.apply {
            project.dependencies.add("jooqImplementation", ASPECTJ)
        }
    }

    private fun Project.addXlintIgnoreForCompileTasks() {
        tasks.named { it.startsWith("compile") }.configureEach {
            it.extensions.findByType(AjcAction::class.java)
        }
    }
}